version: '3.8'
services:
  happ-crypto-api:
    image: happ-crypto-api:latest
    container_name: happ-crypto-api
    expose:
      - "3000"
    networks:
      - happ-crypto-network

  happ-crypto-telegram-admin:
    image: happ-crypto-telegram-admin:latest
    container_name: happ-crypto-telegram-admin
    expose:
      - "3000"
    networks:
      - happ-crypto-network

  happ-crypto-admin:
    image: happ-crypto-admin:latest
    container_name: happ-crypto-admin
    expose:
      - "4000"
    networks:
      - happ-crypto-network

  happ-crypto-nginx:
    image: nginx:alpine
    container_name: happ-crypto-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - happ-crypto-api
      - happ-crypto-admin
      - happ-crypto-telegram-admin
    networks:
      - happ-crypto-network

  happ-crypto-postgres:
    image: postgres:alpine
    container_name: happ-crypto-postgres
    environment:
      POSTGRES_DB: happ-crypto
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - happ-crypto-postgres:/var/lib/postgresql/data
    networks:
      - happ-crypto-network
    ports:
      - "5432:5432"

networks:
  happ-crypto-network:
    driver: bridge

volumes:
  happ-crypto-postgres:
