export enum EventsEnum {
	SOLANA_TRANSACTION = "SOLANA_TRANSACTION",
	SOLANA_TRANSACTION_FAILED = "SOLANA_TRANSACTION_FAILED",
	HELIUS_OPEN = "HELIUS_OPEN",
	HELIUS_ERROR = "HELIUS_ERROR",
	HELIUS_CLOSE = "HELIUS_CLOSE",
	SOLANA_MESSAGE = "SOLANA_MESSAGE",
	MILESTONE_CHECKED = "MILESTONE_CHECKED",
	MILESTONE_CONFIRMED = "MILESTONE_CONFIRMED",
	NEW_POOL_DETECTED = "NEW_POOL_DETECTED"
}
