name: Deploy to prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create empty environment file
        run: echo "${{ secrets.PROD_ENV_BASE64 }}" | base64 -d > ./src/environments/environment.ts

      - name: Decode and create prod environment file
        run: echo "${{ secrets.PROD_ENV_BASE64 }}" | base64 -d > ./src/environments/environment.prod.ts

      - name: Decode and create CA certificate file
        run: |
          echo "${{ secrets.CA_CERTIFICATE_BASE64 }}" | base64 -d > ./ca-certificate.crt

      - name: Build Docker image
        run: docker build -t trading-service .

      - name: Save Docker image
        run: docker save -o trading-service.tar trading-service

      - name: Set permissions for Docker image file
        run: chmod 644 trading-service.tar

      - name: Copy Docker image via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          overwrite: true
          source: "trading-service.tar"
          target: "/home/docker-images"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            docker load -i /home/docker-images/trading-service.tar
            cd /home
            docker-compose up -d --build --no-deps trading-service
